// sram_controller.v

// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module sram_controller (
		input  wire [19:0] sram_avalon_sram_slave_address,       //  sram_avalon_sram_slave.address
		input  wire [1:0]  sram_avalon_sram_slave_byteenable,    //                        .byteenable
		input  wire        sram_avalon_sram_slave_read,          //                        .read
		input  wire        sram_avalon_sram_slave_write,         //                        .write
		input  wire [15:0] sram_avalon_sram_slave_writedata,     //                        .writedata
		output wire [15:0] sram_avalon_sram_slave_readdata,      //                        .readdata
		output wire        sram_avalon_sram_slave_readdatavalid, //                        .readdatavalid
		input  wire        sram_clk_clk,                         //                sram_clk.clk
		inout  wire [15:0] sram_external_interface_DQ,           // sram_external_interface.DQ
		output wire [19:0] sram_external_interface_ADDR,         //                        .ADDR
		output wire        sram_external_interface_LB_N,         //                        .LB_N
		output wire        sram_external_interface_UB_N,         //                        .UB_N
		output wire        sram_external_interface_CE_N,         //                        .CE_N
		output wire        sram_external_interface_OE_N,         //                        .OE_N
		output wire        sram_external_interface_WE_N,         //                        .WE_N
		input  wire        sram_reset_reset                      //              sram_reset.reset
	);

	sram_controller_sram sram (
		.clk           (sram_clk_clk),                         //                clk.clk
		.reset         (sram_reset_reset),                     //              reset.reset
		.SRAM_DQ       (sram_external_interface_DQ),           // external_interface.export
		.SRAM_ADDR     (sram_external_interface_ADDR),         //                   .export
		.SRAM_LB_N     (sram_external_interface_LB_N),         //                   .export
		.SRAM_UB_N     (sram_external_interface_UB_N),         //                   .export
		.SRAM_CE_N     (sram_external_interface_CE_N),         //                   .export
		.SRAM_OE_N     (sram_external_interface_OE_N),         //                   .export
		.SRAM_WE_N     (sram_external_interface_WE_N),         //                   .export
		.address       (sram_avalon_sram_slave_address),       //  avalon_sram_slave.address
		.byteenable    (sram_avalon_sram_slave_byteenable),    //                   .byteenable
		.read          (sram_avalon_sram_slave_read),          //                   .read
		.write         (sram_avalon_sram_slave_write),         //                   .write
		.writedata     (sram_avalon_sram_slave_writedata),     //                   .writedata
		.readdata      (sram_avalon_sram_slave_readdata),      //                   .readdata
		.readdatavalid (sram_avalon_sram_slave_readdatavalid)  //                   .readdatavalid
	);

endmodule
